## image negative

In [12]:
import cv2
import numpy as np

img = cv2.imread('leena.jpg')

print(img.dtype)
print(img.max())
img1_max=img.max()
img_neg = img1_max - img

cv2.imshow('negative',img_neg)
cv2.waitKey(0)

uint8
255


-1

### log transformation

In [4]:
import cv2
import numpy as np

image = cv2.imread('leena.jpg')

c = 255 / np.log(1 + 255)
print(c)
log_image = c * (np.log(image + 1))

log_image = np.array(log_image, dtype = np.uint8)
print(log_image)
cv2.imshow("",image)

cv2.imshow("",log_image)

cv2.waitKey(0)

45.98590442833571
[[[217 226 249]
  [217 225 249]
  [219 226 249]
  ...
  [212 212 241]
  [226 225 248]
  [229 226 248]]

 [[216 225 249]
  [217 225 249]
  [218 225 249]
  ...
  [216 214 242]
  [212 209 239]
  [207 199 233]]

 [[215 225 248]
  [216 225 248]
  [218 225 249]
  ...
  [203 198 234]
  [180 167 221]
  [149  82 206]]

 ...

 [[184 154 211]
  [189 168 213]
  [187 170 211]
  ...
  [189 163 215]
  [193 169 217]
  [191 167 218]]

 [[184 153 209]
  [184 158 209]
  [182 159 209]
  ...
  [191 166 216]
  [196 173 219]
  [204 189 228]]

 [[183 153 205]
  [186 158 209]
  [182 151 207]
  ...
  [198 173 220]
  [208 190 229]
  [210 198 234]]]


C:\Users\DELL\AppData\Local\Temp\ipykernel_11908\683077239.py:8: RuntimeWarning: divide by zero encountered in log
  log_image = c * (np.log(image + 1))


-1

### gama transformation

In [10]:
import cv2
import numpy as np

img = cv2.imread('leena.jpg')
img_gamma=c*pow(img,16)
img_new=np.array(img_gamma,dtype=np.uint8)
cv2.imshow('Original image', img)
cv2.imshow('Gamma corrected image', img_new)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Thresholding

In [8]:
import cv2
import numpy as np

img = cv2.imread('leena.jpg')
ret, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
 
cv2.imshow('Binary Threshold', thresh)

cv2.waitKey(0)

-1

In [12]:
import cv2
import numpy as np

img = cv2.imread('leena.jpg')
ret, thresh = cv2.threshold(img, 109, 367, cv2.THRESH_TRUNC)
 
cv2.imshow('Truncate Threshold', thresh)

cv2.waitKey(0)

-1

In [17]:
import cv2
import numpy as np

img = cv2.imread('leena.jpg')
print(img.shape)
ret, thresh = cv2.threshold(img, 127, 267, cv2.THRESH_TOZERO)
 
cv2.imshow('zero Threshold', thresh)

cv2.waitKey(0)

(129, 129, 3)


-1

### user defined thresholding value

In [25]:

import cv2
import numpy as np

img = cv2.imread('leena.jpg')

def thresholdimg(img, n):
    img_shape = img.shape
   
    for row in range( img_shape[0]):
        for column in range( img_shape[1]):
            if img[column, row] > s:
                img[column, row] = 0
            else:
                img[column, row] = 255
    return 
cv2.imshow(' Threshold', thresh)

cv2.waitKey(0)

-1